### ISSUE TITLE
error when cloning BA repository

### ISSUE THREAD

**Issue by abma** [Balanced-Annihilation/Balanced-Annihilation#1]
error: unable to create symlink luarules/gadgets/AILoader.lua (File name too long)
error: unable to create symlink luarules/gadgets/ai/BA/assistbehaviour.lua (File name too long)
error: unable to create symlink luarules/gadgets/ai/BA/assisthandler.lua (File name too long)
error: unable to create symlink luarules/gadgets/ai/BA/attackerbehaviour.lua (File name too long)
error: unable to create symlink luarules/gadgets/ai/BA/attackhandler.lua (File name too long)
error: unable to create symlink luarules/gadgets/ai/BA/bomberbehaviour.lua (File name too long)
error: unable to create symlink luarules/gadgets/ai/BA/bomberhandler.lua (File name too long)
error: unable to create symlink luarules/gadgets/ai/BA/bootbehaviour.lua (File name too long)
error: unable to create symlink luarules/gadgets/ai/BA/buildsitehandler.lua (File name too long)
error: unable to create symlink luarules/gadgets/ai/BA/cleanhandler.lua (File name too long)
error: unable to create symlink luarules/gadgets/ai/BA/commonfunctions.lua (File name too long)
error: unable to create symlink luarules/gadgets/ai/BA/countbehaviour.lua (File name too long)
error: unable to create symlink luarules/gadgets/ai/BA/defendbehaviour.lua (File name too long)
error: unable to create symlink luarules/gadgets/ai/BA/defendhandler.lua (File name too long)
error: unable to create symlink luarules/gadgets/ai/BA/factoryregisterbehaviour.lua (File name too long)
error: unable to create symlink luarules/gadgets/ai/BA/getunitfeaturetable.lua (File name too long)
error: unable to create symlink luarules/gadgets/ai/BA/loshandler.lua (File name too long)
error: unable to create symlink luarules/gadgets/ai/BA/maphandler.lua (File name too long)
error: unable to create symlink luarules/gadgets/ai/BA/mexupgradebehaviour.lua (File name too long)
error: unable to create symlink luarules/gadgets/ai/BA/raiderbehaviour.lua (File name too long)
error: unable to create symlink luarules/gadgets/ai/BA/reclaimbehaviour.lua (File name too long)
error: unable to create symlink luarules/gadgets/ai/BA/scouthandler.lua (File name too long)
error: unable to create symlink luarules/gadgets/ai/BA/targethandler.lua (File name too long)
error: unable to create symlink luarules/gadgets/ai/BA/taskAir.lua (File name too long)
error: unable to create symlink luarules/gadgets/ai/BA/taskBot.lua (File name too long)
error: unable to create symlink luarules/gadgets/ai/BA/taskBuild.lua (File name too long)
error: unable to create symlink luarules/gadgets/ai/BA/taskEco.lua (File name too long)
error: unable to create symlink luarules/gadgets/ai/BA/taskVeh.lua (File name too long)
error: unable to create symlink luarules/gadgets/ai/BA/taskqueuebehaviour.lua (File name too long)
error: unable to create symlink luarules/gadgets/ai/BA/taskqueues.lua (File name too long)
error: unable to create symlink luarules/gadgets/ai/BA/turtlehandler.lua (File name too long)
error: unable to create symlink luarules/gadgets/ai/BA/unitlists.lua (File name too long)
error: unable to create symlink luarules/gadgets/ai/BA/wardbehaviour.lua (File name too long)
error: unable to create symlink luarules/gadgets/ai/attackhandler.lua (File name too long)
error: unable to create symlink luarules/gadgets/ai/preload/spring_lua/game.lua (File name too long)
error: unable to create symlink luarules/gadgets/ai/preload/spring_lua/map.lua (File name too long)
error: unable to create symlink luarules/gadgets/ai/preload/spring_lua/metal.lua (File name too long)
error: unable to create symlink luarules/gadgets/ai/preload/spring_lua/unit.lua (File name too long)

**Comment by abma** [comment]
these files are symlinks: you should not use symlinks as afaik these are not supported on windows.

**Comment by abma** [comment]
whatevery you did: conversation of svn->git failed :-|

**Comment by abma** [comment]
wow, this took me 30 minutes to fix.

https://github.com/Balanced-Annihilation/Balanced-Annihilation/pull/2

**Comment by ForbodingAngel** [comment]
They aren't symlinks though O_O

**Comment by ForbodingAngel** [comment]
Nevermind... I lied
wtf?

I'll fix

**Comment by abma** [comment]
i.e.
https://github.com/Balanced-Annihilation/Balanced-Annihilation/tree/master/luarules/gadgets
 	AILoader.lua

or
https://github.com/Balanced-Annihilation/Balanced-Annihilation/tree/master/luarules/gadgets/ai
all files

**Comment by abma** [comment]
just merge the pull request!

https://github.com/Balanced-Annihilation/Balanced-Annihilation/pull/2

**Comment by ForbodingAngel** [comment]
I already fixed it. Only took 2 seconds...

**Comment by abma** [comment]
NO, YOU JUST DELETED ALL FILES. NOW THE AI IS GONE AND YOU CAN'T MERGE THE PULL REQUEST.

**Comment by ForbodingAngel** [comment]
Dude... The AI is there. Chill out...

https://i.imgur.com/oixHHCl.png

**Comment by abma** [comment]
yeah, you are my hero.

fixed already an hour ago: https://github.com/Balanced-Annihilation/Balanced-Annihilation/pull/2

**Comment by ForbodingAngel** [comment]
I honestly didn't see the PR at first and immediately went into "Gotta fix it" mode. I'm sorry for the confusion.

**Comment by abma** [comment]
some files are broken because of your changes:

i.e.:
https://github.com/Balanced-Annihilation/Balanced-Annihilation/blob/master/luarules/gadgets/ai/taskqueuebehaviour.lua

http://imolarpg.dyndns.org/trac/balatest/browser/trunk/luarules/gadgets/ai/taskqueuebehaviour.lua


compare the first line...

**Comment by abma** [comment]
i suggest to revert your changes and merge the pull request

**Comment by ForbodingAngel** [comment]
Ok can do, give me a couple minutes.

**Comment by ForbodingAngel** [comment]
Oh shit  I didn't mean to close this. I was commenting from my phone. My apologies. It has been reverted and the PR merged.

**Comment by abma** [comment]
ok, looks fine now. thanks!
