### ISSUE TITLE
missing texture files

### ISSUE THREAD

**Issue by nixtux** [Balanced-Annihilation/Balanced-Annihilation#10]
[f=-000001] [Texture] Warning: [LoadAndCacheTexture] could not load texture "ANTREFd.dds" from model "objects3d/critter_ant.s3o"
[f=-000001] [Texture] Warning: [LoadAndCacheTexture] could not load texture "Spring unit" from model "objects3d/critter_duck.s3o"
[f=-000001] [Texture] Warning: [LoadAndCacheTexture] could not load texture "chicken2.dds" from model "objects3d/meteor.s3o"

**Comment by ForbodingAngel** [comment]
Bad settings in those models. Requires fixing in upspring. Doesn't cause any visual issues. Low priority.
