### ISSUE TITLE
chat console fails to recognize duplicated lines

### ISSUE THREAD

**Issue by silentwings** [Balanced-Annihilation/Balanced-Annihilation#105]
Type the exact same message in twice, and the chat console will only show it once. There used to be little (2x), (3x) etc indicators in the margin, but they are absent in 10.07, for both old & new style chat consoles.

(It is useful when echoing from code to know exactly how many times something happened.)

**Comment by Fx-Doo** [comment]
This is not a widget change (even though the widget changed)
Engine simply doesnt add duplicates lines to the console anymore.
- Try using tthe new consoles on spring 103, it will still show x2,x3 ....
- Try showing engine console and spamming, lines will only show once!
