### ISSUE TITLE
explosion that rises forever

### ISSUE THREAD

**Issue by silentwings** [Balanced-Annihilation/Balanced-Annihilation#107]
![screen00009](https://user-images.githubusercontent.com/3885930/38777555-19123b22-40a2-11e8-9e29-e2edb74125c0.jpg)
![screen00010](https://user-images.githubusercontent.com/3885930/38777558-1daf884c-40a2-11e8-916b-e197995ef78d.jpg)

Noticed a couple of times before too, but no idea which ceg is responsible.

**Comment by Ruwetuin** [comment]
as far as i know this is an engine bug, its flametrower projectile, not ceg

**Comment by Ruwetuin** [comment]
might be fixed in next ba version due to limiting life to 1 instead of 1.9
