### ISSUE TITLE
Some widgets error out when switching teams with cheats on

### ISSUE THREAD

**Issue by nixtux** [Balanced-Annihilation/Balanced-Annihilation#11]
[f=-000001] Error in IsAbove(): [string "LuaUI/Widgets_BA/gui_clearmapmarks.lua"]:133: attempt to perform arithmetic on global 'usedImgSize' (a nil value)

[f=-000001] Error in IsAbove(): [string "LuaUI/Widgets_BA/gui_discord.lua"]:145: attempt to perform arithmetic on global 'usedImgSize' (a nil value)

**Comment by ForbodingAngel** [comment]
You gave 0 information. This is not an error that would normally happen. Did it happen when you switched teams with cheats on?

**Comment by nixtux** [comment]
Sorry no cheats involved just started a game didn't even have to touch a unit or command for the error to show.

**Comment by Ruwetuin** [comment]
I dont have this error, may it be the case that you have a custom advplayerslist installed?

**Comment by ForbodingAngel** [comment]
Possibly fixed in a9c99f9, Needs more testing.

**Comment by ForbodingAngel** [comment]
Another error cropped up. Easy fix as it was just a nil.

This issue is fixed in it's entirety in 3a7fe15
