### ISSUE TITLE
[f=-000001] Error: [LuaRules::RunCallInTraceback] error=2 (LUA_ERRRUN) callin=AllowStartPosition trace=[Internal Lua error: Call failure] [string "LuaRules/Gadgets/game_replace_afk_players.l..."]:114: attempt to index local 'customtable' (a boolean value)

### ISSUE THREAD

**Issue by silentwings** [Balanced-Annihilation/Balanced-Annihilation#113]
@& loads of similar, every game, with latest ba-test on -557

would offer to look at it, since i wrote the thing, but am away from home for a while, so can't

**Comment by Ruwetuin** [comment]
aready fixed in https://github.com/Balanced-Annihilation/Balanced-Annihilation/commit/2f186d5b8ec7cae2a5bac8a540b729c6dc1f07a6
