### ISSUE TITLE
[Music Player] Widget errors if it doesn't find any tracks

### ISSUE THREAD

**Issue by nixtux** [Balanced-Annihilation/Balanced-Annihilation#12]
[f=-000001] Error in Update(): [string "LuaUI/Widgets_BA/snd_music.lua"]:111: bad argument #2 to 'random' (interval is empty)

**Comment by ForbodingAngel** [comment]
It's known. There isn't much point to make an issue of it. It's caused because it can't find any music tracks. There is a fix in play, but I haven't had time to fix it yet and this falls a ways down the priority list.
