### ISSUE TITLE
Missing BAR units

### ISSUE THREAD

**Issue by Beherith** [Balanced-Annihilation/Balanced-Annihilation#141]
Please tell me which units dont have BAR counterparts yet. It would help me tons if you screenshotted the units and gave me a general description of what they do (weapon types, count, size, tier, land/hover/etc)

**Comment by Fx-Doo** [comment]
Hey there !
The units without BAR conterparts are mostly sea units, as some were added, and others had their models changed.
- **armlun** = Arm Tech3 Hovercraft: bulldog-sized, quite bulky, with a single double barrel weapon (cannon weapon, firing shells that can also aim underwater)
- **corsok** = Core Tech3 Hovercraft: Similar size to a penetrator, with a single laser weapon that towers high enough, high reloadtime and beamtime.
- arm/cor **uwmex** = Tech1 Arm/Core offshore mexes: the models might be a little tricky to make. They consist of 3 parts: an upper one that can be submerged when turned off, a bottom one that sits at the sea floor, and a medium part that links both, and is a repetitive pattern of "levels" (this allows the script to move/hide those "levels" to adjust the overall height of the unit and fit the ground level)

The next ones already have a BAR model that either flow or I made:
- **armpship** = Tech1 Arm plasma ship: size inbetween destroyer/corvette, with 2 double barreled light plasma cannons (similar to the hammers' weapons)
- **corpship** = Tech1 Core plasma ship: size inbetween destroyer/corvette, slightly heavier than arm, with 1 triple barreled light plasma cannons (slightly heavier than its arm counterpart)
- arm/cor **gplat** = Tech1 Arm/Core "gunplatform", which have the same footprint as the arm/cor frt but are lower/flatter. They're double barreled high vel/firerate cannons placed on floaters, used against both boats and air.
- arm/cor **nanotcplat** = Tech1 Arm/Core "nano platform", which are very similar to their land counterpart, with floaters

Then we have 6 other units that are not/might not be used in the current or the next versions, so i'm unsure as to wether or not it is worth bothering at all:
- arm/cor **dship** = Arm/Core Tech 1 depthcharge frigate (same size as plasma ships) with a single DC weapon [[currently used but might be removed]]
- arm/cor **rship** = Arm/Core Tech 1 missile frigate (same size as plasma ships) with a single light missile launcher weapon [[currently unused]]
- arm/cor **frock** = Arm/Core tech 1 floating SAM, similar to the packo/core counterpart with floaters. [[currently unused]]

I believe that is about all for the units that were added/modified after the BAR models were made.

**Comment by silentwings** [comment]
BAR units were moved out of this repo!
