### ISSUE TITLE
Where is unit outline option?

### ISSUE THREAD

**Issue by triton13** [Balanced-Annihilation/Balanced-Annihilation#152]

**Comment by triton13** [comment]
Units outline used to make nice cell shading effects, I cannot find the option anymore on test version

**Comment by nixtux** [comment]
It's been removed https://github.com/Balanced-Annihilation/Balanced-Annihilation/commit/ef3fac90222dbe492feed2ff6b32fd8299d20fa3
Just add it locally if you miss it that much problem solved, https://raw.githubusercontent.com/Balanced-Annihilation/Balanced-Annihilation/03d7e9c03f9103b817ee14cacbd7f7342588a99a/luaui/Widgets_BA/gfx_outline.lua

**Comment by triton13** [comment]
no way, this widget is amazing, just don't remove it

**Comment by silentwings** [comment]
gfx_outline.lua has terrible performance - at least on my system - far below what could be distributed with a "this is OK to use" implication (even with default off, but vbs is right, it was default on)

https://cdn.discordapp.com/attachments/439724246797778965/579540347168751617/screen00109.png

has to go, the issue can be re-opened if better code for it exists / is written
