### ISSUE TITLE
revert https://github.com/Balanced-Annihilation/Balanced-Annihilation/commit/14f63b091f36cb7361be23f92bf536ecb1cab8bd#diff-4bcd7eaf5dad39667f91c0ab762e3c9f

### ISSUE THREAD

**Issue by triton13** [Balanced-Annihilation/Balanced-Annihilation#153]
https://github.com/Balanced-Annihilation/Balanced-Annihilation/commit/14f63b091f36cb7361be23f92bf536ecb1cab8bd#diff-4bcd7eaf5dad39667f91c0ab762e3c9f

**Comment by silentwings** [comment]
gfx_outline.lua has terrible performance - at least on my system - far below what could be distributed with a "this is OK to use" implication (even with default off, but vbs is right, it was default on)

https://media.discordapp.net/attachments/439724246797778965/579540347168751617/screen00109.png?width=400&height=241

**Comment by silentwings** [comment]
I've not managed to find anything broken here. I can pause the game without errors.

**Comment by triton13** [comment]
the issue happens when you have connection problems

**Comment by silentwings** [comment]
what is the issue and how do i replicate it?

**Comment by triton13** [comment]
simulate connection problem? last time I had lags the game was pausing/unpausing alone

**Comment by silentwings** [comment]
"connection problem" is not specific enough to allow me to do anything here

**Comment by Ruwetuin** [comment]
i said to triton to undo that commit, cause it shows pause screen when someone's game lags/freezes for a bit

**Comment by silentwings** [comment]
i see, thanks

**Comment by silentwings** [comment]
might be fixed, but since i can't easily induce network i haven't actually tested 

re-open if needed
