### ISSUE TITLE
tac nuke crashes?

### ISSUE THREAD

**Issue by silentwings** [Balanced-Annihilation/Balanced-Annihilation#162]
from https://springrts.com/phpbb/viewtopic.php?p=594941#p594941, i won't take it on

"please help with fixing the crash issue produced in GNU/Linux.
Some players we have problems to play BA because of this issue.
Some units like tactical nuke makes SpringRTS/BA to crash."

**Comment by silentwings** [comment]
apparently its already fixed in spring 104 https://springrts.com/phpbb/viewtopic.php?p=594951#p594951

**Comment by Are-s** [comment]
already fixed last year
