### ISSUE TITLE
BA sets SmallFontFile / FontFile with invalid values

### ISSUE THREAD

**Issue by abma** [Balanced-Annihilation/Balanced-Annihilation#186]
when spring is compiled / run in source, then the build system sets

SmallFontFile / FontFile to absolute paths.

when BA started it seems it resets these values to invalid values.

i.e.:

FontFile = /home/abma/dev/spring/cont/fonts/FreeSansBold.otf
SmallFontFile = /home/abma/dev/spring/cont/fonts/FreeSansBold.otf

->

FontFile = FreeSansBold.otf
SmallFontFile = FreeSansBold.otf

after this change spring fails to start with 
"Failed to load FontFile "FreeSansBold.otf", did you forget to run make install?"

so, please just don't touch this config setting as IMHO its not needed as afaik no other font is used at all.

**Comment by CommanderSpice** [comment]
This is the offending widget: https://github.com/Balanced-Annihilation/Balanced-Annihilation/blob/656013b610bf9d6b1f3ac938198a547d7a9965f2/luaui/widgets/set_springsettings_defaults.lua#L177

Similar to the 'Options' widget, this toggles widgets and fscks with the engine settings.
It will be dropped or neutered in the spring-106 branch.

Keeping this open in case @Are-s wants to fix this in master. I think the the widget should  reset the settings to the defaults once.

**Comment by CommanderSpice** [comment]
Games have no business touching this settings.
I should be able to set my font to Exocet in `springsettings.cfg` once and all games have to respect that.

But I don't care about the 105 branch, so this is OK for me.

**Comment by Are-s** [comment]
Each mod has its own unique settings and they override each other every time you launch a different game. BA is currently setup to remember your settings even if you launch different games. Simply set them in the settings menu. If a font is missing just add it to the game. No user should have to touch the springsettings file

**Comment by CommanderSpice** [comment]
I think it would be best if games stopped pretending to know better how users want to run their engine. I also noticed that this is prone to break spring-headless or impact its performance: some settings have headless defaults for a reason.

Ill-behaved games breaking the configuration can probably be mitigated in the engine by providing two commands to set a configuration value: one that only sets the value for the session and one that sets it and writes it to the configuration file. As the games have to assume they need to setup everything at startup anyway, there would be no reason for them to call the persistent 'set' command.

BA-106 does not touch `springsettings.cfg`.
