### ISSUE TITLE
Consider making mexes amphibious

### ISSUE THREAD

**Issue by sprunk** [Balanced-Annihilation/Balanced-Annihilation#36]
Removes the need for a separate UW mex. Ditto for moho.

**Comment by ForbodingAngel** [comment]
I wholeheartedly agree with this. I'll try to get Floris on board :-)

**Comment by Ruwetuin** [comment]
I reverted this due to land builders wanting to make water mexes, also land mexes in water is looking odd

**Comment by ForbodingAngel** [comment]
Fwiw, I think that is a terrible reason.

**Comment by sprunk** [comment]
Block building sea mexes for land cons (and vice versa).
Get a combined model that switches between UW and regular.

**Comment by Ruwetuin** [comment]
how to remove luamex... or just disabling the user/gui parts of it from BA?

**Comment by Ruwetuin** [comment]
reverted to old metal extractor situation
