### ISSUE TITLE
is a release planned soon?

### ISSUE THREAD

**Issue by abma** [Balanced-Annihilation/Balanced-Annihilation#4]
ba:stable is currently broken, aww....

thats because of some optimization which causes only to fetch the ba repo when the prefix in repos.gz matches which is the case here :-|

**Comment by Ruwetuin** [comment]
no, not that soon... maybe in a few weeks

**Comment by abma** [comment]
uah, ok. fixed in a very ugly way: copied ba:stable from the svn repo to git and... i hope it works/for me it worked in my test :-|
