### ISSUE TITLE
could not load 'LuaUI/utils.lua

### ISSUE THREAD

**Issue by abma** [Balanced-Annihilation/Balanced-Annihilation#51]
just tried ba:test in the latest spring engine. I'm getting this error:

[f=-000001] Reloading GUI config from file: LuaUI/ctrlpanel.txt
[f=-000001] Error: [LuaUI::RunCallInTraceback] error=2 (LUA_ERRRUN) callin=Initialize trace=[Internal Lua error: Call failure] Include() could not load 'LuaUI/utils.lua'
stack traceback:
	[C]: in function 'Include'
	[string "-------------------------------------------..."]:16: in function 'chunk'
	[string "luaui.lua"]:50: in main chunk

**Comment by abma** [comment]
oh, broken spring install, sorry

**Comment by Ruwetuin** [comment]
thanks anyway
