### ISSUE TITLE
KAIK broken due to removal of engine support for mexextract

### ISSUE THREAD

**Issue by abma** [Balanced-Annihilation/Balanced-Annihilation#52]
it seems https://github.com/Balanced-Annihilation/Balanced-Annihilation/commit/e5aaf26b6f1b6df9009152f01d05e620ffc2fff0 broke KAIK.

how can an AI detect which unit is a metal extractor?

**Comment by abma** [comment]
is 
customparams = {
 			death_sounds = "generic",
			metal_extractor = 1
}

"official" ?!

**Comment by ForbodingAngel** [comment]
That is how luamex sees extractors. Luamex bypasses the engine's method entirely (this is a good thing) and puts it in a form that can be easily manipulated and controlled.

Luamex uses that customparam to know which units are seen as mexes. Otherwise, you would look in the unitdef for extractsmetal = <not NIL>

**Comment by abma** [comment]
> Luamex bypasses the engine's method entirely (this is a good thing) 

why is this good? its not good as it breaks existing stuff!

**Comment by ForbodingAngel** [comment]
Like relying on a unitdef tag? Please. Resources are far better when handled via lua. In fact, there have been big pushes in the past to pull metal and energy out of the engine and put it into lua. Far easier to manipulate, far easier to control.

**Comment by abma** [comment]
using a non-standard way makes it much more difficult to auto recognize the type of a unit.

zero-k uses ismex:
https://github.com/ZeroK-RTS/Zero-K/blob/master/units/staticmex.lua#L24

what is missing in the engine which required to implement it lua?

**Comment by abma** [comment]
also side note: i didn't test other ai's.

**Comment by Ruwetuin** [comment]
sounds like uniformity/compatibility wise it whould be renamed to ismex i guess...

...that said, I cant sell luamex to the playerbase as it is....

**Comment by ForbodingAngel** [comment]
No, @Ruwetuin , you aren't understanding. It is ZK that is out of compatibility. Multiple games (4 or 5 by my last count) use luamex and Sprunk and I worked on, from the repo.

ZK uses a very old and outdated luamex that is very much formed to work for ZK and ZK only.

**Comment by abma** [comment]
both is non-standard, thats why its "customparams" :)

what was missing in the engine which required to implement it in lua?

**Comment by Ruwetuin** [comment]
reverted to old metal extractor situation
