### ISSUE TITLE
ShardLuaAI error: luarules/gadgets/ai/BA/maphandler.lua"]:983: table index is NaN

### ISSUE THREAD

**Issue by abma** [Balanced-Annihilation/Balanced-Annihilation#54]
[f=-000001] Error: [LuaRules::RunCallInTraceback] error=2 (LUA_ERRRUN) callin=UnitCreated trace=[Internal Lua error: Call failure] [string "luarules/gadgets/ai/BA/maphandler.lua"]:983: table index is NaN
stack traceback:
	[string "luarules/gadgets/ai/BA/maphandler.lua"]:983: in function 'factoriesRating'
	[string "luarules/gadgets/ai/BA/maphandler.lua"]:629: in function 'Init'
	[string "luarules/gadgets/ai/ai.lua"]:38: in function 'Init'
	[string "LuaRules/Gadgets/ailoader.lua"]:85: in function 'prepareTheAI'
	[string "LuaRules/Gadgets/ailoader.lua"]:280: in function 'UnitCreated'
	[string "LuaRules/gadgets.lua"]:1239: in function <[string "LuaRules/gadgets.lua"]:1237>
	(tail call): ?
	[C]: in function 'spCreateUnit'
	[string "LuaRules/Gadgets/game_initial_spawn.lua"]:431: in function 'SpawnStartUnit'
	[string "LuaRules/Gadgets/game_initial_spawn.lua"]:412: in function 'SpawnTeamStartUnit'
	[string "LuaRules/Gadgets/game_initial_spawn.lua"]:343: in function 'GameStart'
	[string "LuaRules/gadgets.lua"]:826: in function <[string "LuaRules/gadgets.lua"]:824>
	(tail call): ?

**Comment by abma** [comment]
[f=-000001] Shard by AF - playing:BA on:airport 0.7

**Comment by Ruwetuin** [comment]
i know nothing about ai stuff...

**Comment by abma** [comment]
very likely its caused by a map without mex spots

**Comment by Ruwetuin** [comment]
reverted to old metal extractor situation

**Comment by Ruwetuin** [comment]
removed shard lua ai

**Comment by abma** [comment]
thanks a lot!

**Comment by TurBoss** [comment]
sorry but my maps were made for my game (without mexes in mind) but they where spread :)
