### ISSUE TITLE
ShardLuaAI Errors:  "luarules/gadgets/ai/unit.lua"]:83: attempt to index local 'unit' (a nil value)

### ISSUE THREAD

**Issue by abma** [Balanced-Annihilation/Balanced-Annihilation#55]
happened in a test game when starting Arm Juni (Anti Mine/Radar/...weapon):

[f=0088641] Error: [LuaRules::RunCallInTraceback] error=2 (LUA_ERRRUN) callin=UnitDamaged trace=[Internal Lua error: Call failure] [string "luarules/gadgets/ai/unit.lua"]:83: attempt to index local 'unit' (a nil value)
stack traceback:
	[string "luarules/gadgets/ai/unit.lua"]:83: in function 'UnitDamaged'
	[string "luarules/gadgets/ai/unithandler.lua"]:79: in function 'UnitDamaged'
	[string "luarules/gadgets/ai/ai.lua"]:131: in function 'UnitDamaged'
	[string "LuaRules/Gadgets/ailoader.lua"]:322: in function 'UnitDamaged'
	[string "LuaRules/gadgets.lua"]:1352: in function <[string "LuaRules/gadgets.lua"]:1339>
	(tail call): ?
[f=0088643] Error: [LuaRules::RunCallInTraceback] error=2 (LUA_ERRRUN) callin=GameFrame trace=[Internal Lua error: Call failure] [string "luarules/gadgets/ai/BA/targethandler.lua"]:150: attempt to index local 'pos' (a nil value)
stack traceback:
	[string "luarules/gadgets/ai/BA/targethandler.lua"]:150: in function 'GetCellPosition'
	[string "luarules/gadgets/ai/BA/targethandler.lua"]:190: in function 'GetOrCreateCellHere'
	[string "luarules/gadgets/ai/BA/targethandler.lua"]:532: in function 'UpdateDamagedUnits'
	[string "luarules/gadgets/ai/BA/targethandler.lua"]:755: in function 'UpdateMap'
	[string "luarules/gadgets/ai/BA/targethandler.lua"]:940: in function 'GetNearestAttackCell'
	[string "luarules/gadgets/ai/BA/attackhandler.lua"]:151: in function 'SquadReTarget'
	[string "luarules/gadgets/ai/BA/attackhandler.lua"]:311: in function 'SquadAdvance'
	[string "luarules/gadgets/ai/BA/attackhandler.lua"]:279: in function 'SquadPathfind'
	[string "luarules/gadgets/ai/BA/attackhandler.lua"]:58: in function 'Update'
	[string "luarules/gadgets/ai/ai.lua"]:52: in function 'Update'
	[string "LuaRules/Gadgets/ailoader.lua"]:266: in function 'GameFrame'
	[string "LuaRules/gadgets.lua"]:840: in function <[string "LuaRules/gadgets.lua"]:838>
	(tail call): ?
[f=0088645] Error: [LuaRules::RunCallInTraceback] error=2 (LUA_ERRRUN) callin=GameFrame trace=[Internal Lua error: Call failure] [string "luarules/gadgets/ai/BA/targethandler.lua"]:150: attempt to index local 'pos' (a nil value)
stack traceback:
	[string "luarules/gadgets/ai/BA/targethandler.lua"]:150: in function 'GetCellPosition'
	[string "luarules/gadgets/ai/BA/targethandler.lua"]:190: in function 'GetOrCreateCellHere'
	[string "luarules/gadgets/ai/BA/targethandler.lua"]:532: in function 'UpdateDamagedUnits'
	[string "luarules/gadgets/ai/BA/targethandler.lua"]:755: in function 'UpdateMap'
	[string "luarules/gadgets/ai/BA/targethandler.lua"]:1252: in function 'ThreatHere'
	[string "luarules/gadgets/ai/BA/targethandler.lua"]:1290: in function 'IsSafePosition'
	[string "luarules/gadgets/ai/BA/scoutbehaviour.lua"]:75: in function 'Update'
	[string "luarules/gadgets/ai/unit.lua"]:28: in function 'Update'
	[string "luarules/gadgets/ai/unithandler.lua"]:30: in function 'Update'
	[string "luarules/gadgets/ai/ai.lua"]:52: in function 'Update'
	[string "LuaRules/Gadgets/ailoader.lua"]:266: in function 'GameFrame'
	[string "LuaRules/gadgets.lua"]:840: in function <[string "LuaRules/gadgets.lua"]:838>
	(tail call): ?
[f=0088646] Error: [LuaRules::RunCallInTraceback] error=2 (LUA_ERRRUN) callin=GameFrame trace=[Internal Lua error: Call failure] [string "luarules/gadgets/ai/BA/targethandler.lua"]:150: attempt to index local 'pos' (a nil value)
stack traceback:
	[string "luarules/gadgets/ai/BA/targethandler.lua"]:150: in function 'GetCellPosition'
	[string "luarules/gadgets/ai/BA/targethandler.lua"]:190: in function 'GetOrCreateCellHere'
	[string "luarules/gadgets/ai/BA/targethandler.lua"]:532: in function 'UpdateDamagedUnits'
	[string "luarules/gadgets/ai/BA/targethandler.lua"]:755: in function 'UpdateMap'
	[string "luarules/gadgets/ai/BA/targethandler.lua"]:1252: in function 'ThreatHere'
	[string "luarules/gadgets/ai/BA/targethandler.lua"]:1290: in function 'IsSafePosition'
	[string "luarules/gadgets/ai/BA/scoutbehaviour.lua"]:75: in function 'Update'
	[string "luarules/gadgets/ai/unit.lua"]:28: in function 'Update'
	[string "luarules/gadgets/ai/unithandler.lua"]:30: in function 'Update'
	[string "luarules/gadgets/ai/ai.lua"]:52: in function 'Update'
	[string "LuaRules/Gadgets/ailoader.lua"]:266: in function 'GameFrame'
	[string "LuaRules/gadgets.lua"]:840: in function <[string "LuaRules/gadgets.lua"]:838>
	(tail call): ?
[f=0088647] Error: [LuaRules::RunCallInTraceback] error=2 (LUA_ERRRUN) callin=GameFrame trace=[Internal Lua error: Call failure] [string "luarules/gadgets/ai/BA/targethandler.lua"]:150: attempt to index local 'pos' (a nil value)
stack traceback:
	[string "luarules/gadgets/ai/BA/targethandler.lua"]:150: in function 'GetCellPosition'
	[string "luarules/gadgets/ai/BA/targethandler.lua"]:190: in function 'GetOrCreateCellHere'
	[string "luarules/gadgets/ai/BA/targethandler.lua"]:532: in function 'UpdateDamagedUnits'
	[string "luarules/gadgets/ai/BA/targethandler.lua"]:755: in function 'UpdateMap'
	[string "luarules/gadgets/ai/BA/targethandler.lua"]:940: in function 'GetNearestAttackCell'
	[string "luarules/gadgets/ai/BA/attackhandler.lua"]:151: in function 'SquadReTarget'
	[string "luarules/gadgets/ai/BA/attackhandler.lua"]:311: in function 'SquadAdvance'
	[string "luarules/gadgets/ai/BA/attackhandler.lua"]:279: in function 'SquadPathfind'
	[string "luarules/gadgets/ai/BA/attackhandler.lua"]:58: in function 'Update'
	[string "luarules/gadgets/ai/ai.lua"]:52: in function 'Update'
	[string "LuaRules/Gadgets/ailoader.lua"]:266: in function 'GameFrame'
	[string "LuaRules/gadgets.lua"]:840: in function <[string "LuaRules/gadgets.lua"]:838>
	(tail call): ?
[f=0088648] Fatal: LuaRules: cannot allocate more memory! (805306415 bytes already used, 805306368 bytes maximum)
[f=0088648] Error: [LuaRules::RunCallInTraceback] error=4 (LUA_ERRMEM) callin=GameFrame trace=[Internal Lua error: Call failure] not enough memory

**Comment by abma** [comment]
side note: memory usage of an lua ai seems to count into lua memory, too. -> lua ai mem leak will kill the entire game including luaui.

**Comment by Ruwetuin** [comment]
cant we remove the entire lua ai thing?

**Comment by abma** [comment]
sadly yep. without a maintainer / beeing more stable its not this useful :-|

-> should be implemented so it can be readded / added as dedicated archive without interfering luaui / gadgets: https://github.com/spring/Shard/issues/2

**Comment by Ruwetuin** [comment]
apart from removing the gadgets/ai directory... anything else need to be done?

**Comment by abma** [comment]
+ /LuaAI.lua afaik, that should be all.

**Comment by abma** [comment]
http://imolarpg.dyndns.org/trac/balatest/changeset/5566

**Comment by Ruwetuin** [comment]
removed it

**Comment by ForbodingAngel** [comment]
Fwiw, I made my own mutator so that I could keep using shardlua, as it never messes up for me. The shard config seems to work reasonably well too. Course, most of the time I play on red/green comet. Shard does nicely on that map, so it's easier to just play the same map than to figure out what maps shard shits itself, etc.

**Comment by ForbodingAngel** [comment]
Additionally, I never addressed this issue, but why not simply just add a nil check to unit.lua instead of removing it altogether?
