### ISSUE TITLE
infolog warning

### ISSUE THREAD

**Issue by nixtux** [Balanced-Annihilation/Balanced-Annihilation#7]
[f=-000001] Warning: too many unit categories (32), skipping sub

**Comment by ForbodingAngel** [comment]
First off, this is not a bug that needs to be fixed. It is merely an annoyance. For the most part, the categories in BA are largely superficial and redundant. It would require a herculean effort to fix them properly. Considering that the amount of categories is not actually causing any real issues (other than being annoying), they will be fixed when someone has time to spend 2 weeks sorting through 346 unit files.

**Comment by nixtux** [comment]
Well if you had actually spent at least 2 mins looking into the issue instead of writing it off straight from the bat, you would have noticed that the issue is only created by one unit https://github.com/Balanced-Annihilation/Balanced-Annihilation/blob/master/units/critters/critter_goldfish.lua

**Comment by ForbodingAngel** [comment]
No, the issue is not just this unit. The issue is that superflous unit categories are used all throughout the game. As a result, it needs to be fixed t some point. When I fix an issue, I don't just bandaid it, I fix it. If you just "out of sight, out of mind" every issue, then you end up with the gigantic mess that is current stable BA which me and Floris have been fixing.

**Comment by nixtux** [comment]
Forbs stop talking BS I completed that now there is one extra category called sub I found which unit was causing issue and you are dismissing it. Your whole attitude sucks I'm trying to help and all you do is throw it back in my face please remove my account from ba access I won't help you again. Have fun breaking BA.

**Comment by nixtux** [comment]
And just to make a point the bug was introduced with this commit https://github.com/Balanced-Annihilation/Balanced-Annihilation/commit/a2e08d995883274588e3d998ce061943d90ce519
Ergo it is a regression as this error was not there before. So i take i you now saying its fine to push commits which introduce bugs and your not going to fix them.

**Comment by ForbodingAngel** [comment]
Nix, 32 categories being used IS an issue. I can understand why you might not understand why, coming from a *A standpoint, but it is something that needs to be addressed. That critters triggers an infolog warning is a sidenote. That's what I've been trying to explain to you. It's a symptom of a much larger issue.

**Comment by nixtux** [comment]
And there we go again if you actually checked ba has 31 category's in use 2 incorrrect cats where introduced with the cirtters but meh not going to listen to anyone else but yourself.

**Comment by ForbodingAngel** [comment]
BA should use at max, maybe 5 - 10 categories. That's what I've been trying to explain to you.

**Comment by nixtux** [comment]
Forbs im well aware what you was trying to explain coming from an *A mod which has already done that and imo that a total different issue than the one im post now and should be opened as a new issue, i dont know what i have  done to make you dismiss everything i've said, i tryed to help and say your scripts are wrong (you still have not fixed that issue), any other issue here i posted you moan at me for posting your whole attitude toward anything ive said is so rude. so now i've left the ba team i'm not going to help somewith with the head up there own arse. goodbye
