### ISSUE TITLE
[f=0009548] Error: division by zero (in scripts/corenaa.cob:RockUnit at 89)

### ISSUE THREAD

**Issue by abma** [Balanced-Annihilation/Balanced-Annihilation#70]
happened after /cheat
/give all
/give all 2

[f=0009548] Error: division by zero (in scripts/corenaa.cob:RockUnit at 89)
[f=0009548] Error: division by zero (in scripts/corenaa.cob:RockUnit at 93)
[f=0009550] Error: division by zero (in scripts/corenaa.cob:RockUnit at 89)
[f=0009550] Error: division by zero (in scripts/corenaa.cob:RockUnit at 93)
[f=0009562] -> Commander is being attacked!
[f=0009573] Error: division by zero (in scripts/corenaa.cob:RockUnit at 89)
[f=0009573] Error: division by zero (in scripts/corenaa.cob:RockUnit at 93)
[f=0009599] Error: division by zero (in scripts/corenaa.cob:RockUnit at 89)
[f=0009599] Error: division by zero (in scripts/corenaa.cob:RockUnit at 93)

**Comment by Ruwetuin** [comment]
fixed
