### ISSUE TITLE
Add BAR repo to this organization

### ISSUE THREAD

**Issue by abma** [Balanced-Annihilation/Balanced-Annihilation#74]
would it make sense to add BAR to this github organization?

https://springrts.com/phpbb/viewtopic.php?f=44&t=36353

-> is there any interest in merging BA + BAR?

**Comment by nixtux** [comment]
Imo a separate organisation is needed for BAR.

**Comment by silentwings** [comment]
Behe and I have agreed that the official BAR repo will remain at its current location.

**Comment by abma** [comment]
the ticket sadly gots deleted: svn is still deprecated for rapid. now is a good point to remove it...

ok, seems there is no interest in moving it to the BA repo, i guess floris has the same opinion.

**Comment by abma** [comment]
the ticket sadly gots deleted: svn is still deprecated for rapid. now is a good point to remove it...

ok, seems there is no interest in moving it to the BA repo, i guess floris has the same opinion.

thanks for the feedback.

**Comment by abma** [comment]
https://github.com/Balanced-Annihilation/Balanced-Annihilation/blob/master/modoptions.lua#L22

barmodels!

:heart_eyes: :heart_eyes: :heart_eyes: :heart_eyes: :heart_eyes:
