### ISSUE TITLE
lua errors on start (Unit Definitions)

### ISSUE THREAD

**Issue by abma** [Balanced-Annihilation/Balanced-Annihilation#75]
[f=-000001] Loading Unit Definitions
[f=-000001] Error: WARNING: Couldn't find a MoveClass named boat42x5 (used in UnitDef: armpship)
[f=-000001] Warning: too many unit categories (32), skipping constr
[f=-000001] Warning: removed the "armpship" entry from the "armsy" build menu

to reproduce, start "Balanced Annihilation test-7347-6ccdc6e" (=current ba:test)

**Comment by Fx-Doo** [comment]
Deleted unused category "CONSTR" and added the proper moveclass in movedefs.lua
