### ISSUE TITLE
Gadget errors: game_controlvictory.lua"]:336: attempt to compare nil with number + unit_commando_watch.lua"]:33: attempt to index field 'commando_minelayer' (a nil value)

### ISSUE THREAD

**Issue by abma** [Balanced-Annihilation/Balanced-Annihilation#76]
show up in the validation test:

[f=-000001] Error: Failed to load: game_controlvictory.lua  ([string "LuaRules/Gadgets/game_controlvictory.lua"]:336: attempt to compare nil with number)
[f=-000001] Error: Failed to load: unit_commando_watch.lua  ([string "LuaRules/Gadgets/unit_commando_watch.lua"]:33: attempt to index field 'commando_minelayer' (a nil value)

maybe see http://buildbot.springrts.com/builders/validationtests/builds/5514/steps/validation%20test_3/logs/stdio

(current ba:test)

**Comment by Ruwetuin** [comment]
fixed
