### ISSUE TITLE
gui_options.lua:1264: attempt to index field 'Red Build/Order Menu' (a nil value)

### ISSUE THREAD

**Issue by abma** [Balanced-Annihilation/Balanced-Annihilation#77]
[f=-000001] Error in Initialize(): [string "LuaUI/Widgets_BA/gui_options.lua"]:1264: attempt to index field 'Red Build/Order Menu' (a nil value)

happens because of a basicly empty config file i guess?!

https://github.com/spring/spring/commit/54c1f2e72e48e6e00ad88d5897cdf2dbd76ce487

**Comment by Ruwetuin** [comment]
yes, forgot to ask widget directly instead of looking in the config file
