### ISSUE TITLE
gui_tooltip.lua"]:129: attempt to compare nil with number

### ISSUE THREAD

**Issue by abma** [Balanced-Annihilation/Balanced-Annihilation#78]
last but not least:

[f=-000001] Error in DrawScreen(): [string "LuaUI/Widgets_BA/gui_tooltip.lua"]:129: attempt to compare nil with number

:)

(validation test, too: http://buildbot.springrts.com/builders/validationtests/builds/5514/steps/validation%20test_3/logs/stdio )

**Comment by Ruwetuin** [comment]
fixed
