### ISSUE TITLE
several units are indestructible (spring 104.0+)

### ISSUE THREAD

**Issue by abma** [Balanced-Annihilation/Balanced-Annihilation#79]
when the units die they don't disappear:
i.e. stumpy, shellshocker, pincer, bulldog...

to reproduce:
/give armstump
/give armstump 1

**Comment by Fx-Doo** [comment]
Abma, all vehicles share the same script (aka basictankscript) that adds a certain amount of features.
The issue you're describing seems to be a delay that i added at random times between last hit and blow.


`if severity <= 99 then
		randomnumber = math.random(1,2)
		if randomnumber == 1 then
			f = 1
			while DeathRun()~=1 do
			end
		end
		for count, piece in pairs(piecetable) do

			randomnumber = math.random(1,3)
			if randomnumber == 1 then
				if piece == base then 
				Explode(piece, SFX.EXPLODE_ON_HIT + SFX.FIRE + SFX.SMOKE + SFX.NO_HEATCLOUD + SFX.FALL + SFX.SHATTER) 
				else
				Explode(piece, SFX.EXPLODE_ON_HIT + SFX.FIRE + SFX.SMOKE + SFX.NO_HEATCLOUD + SFX.FALL)
				end
			elseif randomnumber == 2 then
				Explode(piece, SFX.EXPLODE_ON_HIT + SFX.SHATTER + SFX.NO_HEATCLOUD)
			else
				Explode(piece, SFX.SHATTER + SFX.NO_HEATCLOUD)
			end
			Hide(piece)
		end
		return 3`

and
`function DeathRun()
smokePieces = {base, turret}
if f == 1 then
Spring.SetUnitNoSelect(unitID, true)
while f <=25 do
randomnumber = math.random(1,4)
		if randomnumber == 1 then
		smokeCEGName = smokeCEGName1
		elseif randomnumber == 2 then
			smokeCEGName = smokeCEGName2
		elseif randomnumber == 3 then
			smokeCEGName = smokeCEGName3
		else
			smokeCEGName = smokeCEGName4
		end
		EmitRand(smokePieces[math.random(1,2)], smokeCEGName) --CEG name in quotes (string)
Sleep(math.random(5,100))
f = f + 1
end
end
EmitRand(base, "genericunitexplosion-small" )
return 1
end`

This is an animation where unit catches fire and explodes at the end of it.

I believe what you are describing is therefor something I wanted to happen, and not an issue.

**Comment by abma** [comment]
note: i've tested with the development version of spring.

the unit has 0 hp but still can be selected and move arround. it can't shoot / takes no damage / can't be reclaimed.

it seems the affected units never "blow" / die / disappear.

i guess you mean this code?
https://github.com/Balanced-Annihilation/Balanced-Annihilation/blob/eaa437bc07ff06f7d1ab6b72eb87da2640a83b08/scripts/basictankscript.lua#L406

(imo copy+pasta here is bad, you should link to the code next time :))

**Comment by abma** [comment]
where is f declared / initialized?
https://github.com/Balanced-Annihilation/Balanced-Annihilation/blob/eaa437bc07ff06f7d1ab6b72eb87da2640a83b08/scripts/basictankscript.lua#L344

**Comment by Fx-Doo** [comment]
[https://github.com/Balanced-Annihilation/Balanced-Annihilation/blob/eaa437bc07ff06f7d1ab6b72eb87da2640a83b08/scripts/basictankscript.lua#L405](url)

Right before calling DeathRun() and waiting for it to end.
This is made so that while DeathRun() ~= true do wont trigger DeathRun f times (until the first one is true) but once and wait for it to become true.

**Comment by MaDDoXbr** [comment]
Hey @Fx-Doo , that's LUS right? How are you calculating Severity? 'Coz the parameters taken by the 'Killed' callback are different from the COB ones. To make it work properly in my LUS scripts I had to do this:

function script.Killed(recentDamage, maxHealth)
    local severity = recentDamage / maxHealth * 100

**Comment by abma** [comment]
basictankscript.lua#L405

the variable f is global: are you sure that it isn't reset when an other unit dies? does each unit has its own environment? still note: i'm a unitscript noob :)

regardless: some units never die :)

**Comment by Fx-Doo** [comment]
They should do, since every unit use different pieces names but same globals in the script:
	basename = uDef.customParams and uDef.customParams.basename or "base"
	turretname = uDef.customParams and uDef.customParams.turretname or "turret"
Also they don't always have two cannons so some of them are run with flare2= nil and others with flare2 = piece("flare2").
I'll check out if anything else is wrong though, as i just edited parts of the tank script couple days ago.

**Comment by Fx-Doo** [comment]
@MaDDoXbr i'm using:
function script.Killed(recentDamage, maxHealth)
	severity = recentDamage*100/maxHealth

**Comment by abma** [comment]
retested with spring 103.0: the problem described above doesn't happen it seems.

so its a bug introduced by an engine change: not sure if the game or the engine is to blame.

**Comment by abma** [comment]
https://springrts.com/mantis/view.php?id=5800

**Comment by abma** [comment]
'mod bug afaict (gadget errors bringing down LuaRules):

failed to load ('[f=0000002] LuaRules is not loaded'

see infolog.txt

https://springrts.com/mantis/file_download.php?file_id=3574&type=bug


i guess relevant is:

[f=-000001] Error: Failed to load: cmd_raw_move.lua  ([string "LuaRules/gadgets.lua"]:488: attempt to index field 'ghInfo' (a nil value))
[f=-000001] [Metalspot Finder Gadget] Mex Spot Finder Initialising
[f=-000001] [Metalspot Finder Gadget] Detecting mex config from metalmap
[f=-000001] Error: [LuaRules::RunCallInTraceback] error=2 (LUA_ERRRUN) callin=Initialize trace=[Internal Lua error: Call failure] error = 2, LuaRules/gadgets.lua, [string "LuaRules/Gadgets/mex_spot_finder.lua"]:338: attempt to compare number with string
stack traceback:
	[C]: in function 'Include'
	[string "LuaRules/main.lua"]:9: in main chunk

(there are some other errors as well)

**Comment by MaDDoXbr** [comment]
Wasn't cmd_raw_move.lua disabled, since it's now an engine feature (in 104)? How could it trigger errors then?

**Comment by Ruwetuin** [comment]
it was, it detected if spring v104 was running and it disabled itself, anyway, removed it now

**Comment by abma** [comment]
still an error:

[f=-000001] Error: [LuaRules::RunCallInTraceback] error=2 (LUA_ERRRUN) callin=Initialize trace=[Internal Lua error: Call failure] error = 2, LuaRules/gadgets.lua, [string "LuaRules/Gadgets/mex_spot_finder.lua"]:338: attempt to compare number with string
stack traceback:
	[C]: in function 'Include'
	[string "LuaRules/main.lua"]:9: in main chunk

i guess its caused by https://github.com/spring/spring/blob/develop/doc/changelog.txt#L17 (change for spring 105.0)

**Comment by MaDDoXbr** [comment]
According to docs, spGetGroundInfo(x, z) returned string "Type", number "metal". If that 105 changelog is correct, it will return number "idx", string "Type", number "metal" - which would cause a similar error as you're listing. Noob question, how do we detect the engine version to put an "if" there?

**Comment by Ruwetuin** [comment]
if Engine ~= nil and Engine.version ~= nil then   -- v104 compatibility

this is new in v104, and Engine.version returns a string

**Comment by MaDDoXbr** [comment]
Ok, I fixed a couple other nil-related widget errors I found, I also tried to add the mex_spot_finder.lua but I'd need it tested on 104 and 105 since I cant run'em in my OSX laptop.

**Comment by Ruwetuin** [comment]
fixed error = 2, LuaRules/gadgets.lua, [string "LuaRules/Gadgets/mex_spot_finder.lua"]:338: attempt to compare number with string
