### ISSUE TITLE
multiple dead ceg tags

### ISSUE THREAD

**Issue by nixtux** [Balanced-Annihilation/Balanced-Annihilation#8]
[f=-000001] Warning: [CCEG::Load] junoflash: Unknown tag CExpGenSpawner::particlesize
[f=-000001] Warning: [CCEG::Load] junoflash: Unknown tag CExpGenSpawner::particlesizespread
[f=-000001] Warning: [CCEG::Load] table for CEG "mediumExplosionGenericWhite" invalid (parse errors?)
[f=-000001] Warning: [CCEG::Load] table for CEG "smallExplosionGenericWhite" invalid (parse errors?)
[f=-000001] Warning: [CCEG::Load] table for CEG "FLASH1" invalid (parse errors?)

**Comment by ForbodingAngel** [comment]
The first 2 lines are annoyances and don't cause issues.

Floris must have missed a comma in the last 3 somewhere. I'll have a look.

**Comment by ForbodingAngel** [comment]
Last 3 were non-error errors (Errors of stuff that wasn't really used). Fixed anyway.
