### ISSUE TITLE
gui_top_bar.lua"]:680: attempt to perform arithmetic on local 'convValue'

### ISSUE THREAD

**Issue by abma** [Balanced-Annihilation/Balanced-Annihilation#80]
happens on start:
[f=-000001] Error: gl.CreateList: error(2) = [string "LuaUI/Widgets_BA/gui_top_bar.lua"]:680: attempt to perform arithmetic on local 'convValue' (a nil value)

**Comment by Ruwetuin** [comment]
added nil check to it
