### ISSUE TITLE
mex_spot_finder.lua"]:338: attempt to compare number with string

### ISSUE THREAD

**Issue by abma** [Balanced-Annihilation/Balanced-Annihilation#81]
[f=-000001] Error: [LuaRules::RunCallInTraceback] error=2 (LUA_ERRRUN) callin=Initialize trace=[Internal Lua error: Call failure] error = 2, LuaRules/gadgets.lua, [string "LuaRules/Gadgets/mex_spot_finder.lua"]:338: attempt to compare number with string
stack traceback:
	[C]: in function 'Include'
	[string "LuaRules/main.lua"]:9: in main chunk

**Comment by Ruwetuin** [comment]
fixed
