### ISSUE TITLE
Possible Engine issue, needs a hax for BA if possible: Units drop some move orders when they are issued

### ISSUE THREAD

**Issue by Fx-Doo** [Balanced-Annihilation/Balanced-Annihilation#84]
http://replays.springrts.com/replay/2095df5995516cfdb77e5b355e60533b 
Can be seen here multiple times around 10:00: flashes ware given orders in groups but the orders are instantly dropped for some flashes that decide to just idle.

Needs a fix for BA, somehow.

**Comment by Ruwetuin** [comment]
https://www.youtube.com/watch?v=jrqC4cITwmA

**Comment by Ruwetuin** [comment]
fixed in 104 maintenance
