### ISSUE TITLE
multiple lups errors

### ISSUE THREAD

**Issue by nixtux** [Balanced-Annihilation/Balanced-Annihilation#9]
[f=-000001] Error: Failed to load: lups_projectiles.lua  (Include() could not load 'LuaRules/Configs/lups_projectile_fxs.lua')
[f=-000001] Error: Failed to load: lups_napalm.lua  (Include() could not load 'LuaRules/Configs/lups_napalm_fxs.lua')
[f=-000001] Error: Failed to load: lups_projectiles.lua  (Include() could not load 'LuaRules/Configs/lups_projectile_fxs.lua')
[f=-000001] Error: Failed to load: lups_thrusters.lua  (Include() could not load 'LuaRules/Configs/lups_thruster_fxs.lua')

**Comment by ForbodingAngel** [comment]
These are surperflous (optional) configs that are not necessary. Ofc we can squelch the error easily enough. It simply isn't a high priority.

**Comment by ForbodingAngel** [comment]
Fixed.
