### ISSUE TITLE
Beamlaser damage up front

### ISSUE THREAD

**Issue by ForbodingAngel** [Balanced-Annihilation/Balanced-Annihilation#96]
https://github.com/Balanced-Annihilation/Balanced-Annihilation/blob/a204d299e4216822247e26bc4eb22b4fb02505a3/gamedata/alldefs_post.lua#L468

Currently this is only in test versions, but I want to reiterate that I am not comfortable with this being in production. While yes, it does work properly, it also has some downsides as I stated in discord with units that are mobile with long beamtimes. On the beam time to live, spring detaches the beam from the unit and so on a mobile unit with a long beamtime, you can end up with disembodied beams that just look weird.

While I very much support beamlasers doing all their damage up front and I think that it is necessary for a lot of good reasons, this solution may not be the best way to go about it (which is why I had it in a branch... I kinda meant for it to undergo a lot of testing before potentially being merged into master).

At any rate, it's not a huge deal, but I just wanted to caution you against letting this into the wild on a production version, and bring it to your attention in the even that it had been forgotten. :-)

**Comment by Ruwetuin** [comment]
mantissed:
https://springrts.com/mantis/view.php?id=5987
