### ISSUE TITLE
Game fails to start on maps that use mexes.lua

### ISSUE THREAD

**Issue by The-Yak** [Balanced-Annihilation/Balanced-Annihilation#98]
There seems to be an incompatibility between BA and maps that use the crystal ring gadget, example here: https://springfiles.com/sites/default/files/images/spring/spring-maps/screen00015.jpg

This causes the game not to start on maps Violence, Sever, Zed, probably Coagulation Marsh and others. Game is loaded but commander never drops.

Infolog: https://hastebin.com/tuhigoluwi.md

> [f=-000001]
> Error: [LuaRules::RunCallInTraceback] error=2 (LUA_ERRRUN) callin=Initialize trace=[Internal Lua error: >Call failure] error = 2, LuaRules/gadgets.lua, [string "LuaRules/Gadgets/mexes.lua"]:271: attempt to >compare number with string
>stack traceback:
>	[C]: in function 'Include'
>	[string "LuaRules/main.lua"]:9: in main chunk

The offending gadget can be viewed on github: https://github.com/The-Yak/mexes_grounddecal_autoplacer/blob/master/LuaRules/Gadgets/mexes.lua

Might be easier to block the gadget rather then fixing the issue, the crystal rings are superficial.

**Comment by ForbodingAngel** [comment]
groundMetal should be wrapped in tonumber() anyway because apparently it's
possible for that param to return values as strings. This should be fixed
gadget side, most definitely.

As far as ripping the gadget? *shrug*

**Comment by The-Yak** [comment]
Cleanest fix would be to go through each map and replace mexes.lua with raaar's metal system, which is proper and game agnostic.
