### ISSUE TITLE
player stats update rate seems to depend on fps

### ISSUE THREAD

**Issue by abma** [Balanced-Annihilation/Balanced-Annihilation#99]
if some player has disabled vsync then his stats are much more often updated it seems.

the stats should be only updated when last update was xx seconds ago IMHO.

**Comment by abma** [comment]
in other words: for some players its updated ~3 times a second, for some only every 5 seconds it seems.

**Comment by Ruwetuin** [comment]
eh what stats?

**Comment by abma** [comment]
hover with the mouse-cursor over a player in the playerlist -> popup which shows fps / ...

**Comment by Ruwetuin** [comment]
fps number are refreshed every 2 secs only already

**Comment by abma** [comment]
this didn't work when i watched this for some reason...

**Comment by Ruwetuin** [comment]
code is here:
https://github.com/Balanced-Annihilation/Balanced-Annihilation/blob/master/luarules/gadgets/fps_broadcast.lua#L78

**Comment by abma** [comment]
see player adolf:
[demo.zip](https://github.com/Balanced-Annihilation/Balanced-Annihilation/files/1858072/demo.zip)

**Comment by Ruwetuin** [comment]
oh yeah i know, i ve already done some validation so his widget cant do that any longer
